# Generated by Django 5.0.7 on 2024-08-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0002_genomescore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genometag',
            name='tag',
            field=models.CharField(max_length=255, verbose_name='Tag'),
        ),
    ]
