# Generated by Django 5.0.7 on 2024-07-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImportMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time_in_minutes', models.PositiveIntegerField(verbose_name='Upload Time in Minutes')),
                ('inserted_data_count', models.PositiveBigIntegerField(verbose_name='Inserted Data Count')),
                ('errors_count', models.PositiveBigIntegerField(verbose_name='Errors Count')),
                ('csv_file', models.FileField(upload_to='', verbose_name='CSV File')),
            ],
            options={
                'verbose_name': 'CSV Import Meta Data',
                'verbose_name_plural': 'CSV Imports Meta Data',
            },
        ),
    ]
