# Generated by Django 5.0.7 on 2024-08-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_csvimportmetadata_errors_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvimportmetadata',
            old_name='upload_time_in_minutes',
            new_name='upload_time_in_seconds',
        ),
    ]
