# Generated by Django 5.0.7 on 2024-08-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_upload_time_in_minutes_csvimportmetadata_upload_time_in_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimportmetadata',
            name='upload_status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Done', 'Done')], default='Done', max_length=10, verbose_name='Upload Status'),
        ),
    ]
