# Generated by Django 5.0.7 on 2024-08-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_csvimportmetadata_upload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvimportmetadata',
            name='upload_status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Done', 'Done')], default='In Process', max_length=10, verbose_name='Upload Status'),
        ),
    ]
