# Generated by Django 5.0.7 on 2024-07-26 19:22

import django.db.models.deletion
import movie_lens_django.ratings.valitadors
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_movie_moviegenometag_movie_genome_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[movie_lens_django.ratings.valitadors.validate_rating], verbose_name='Rating')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('user', models.PositiveIntegerField(verbose_name='User ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
    ]
