# Generated by Django 5.0.7 on 2024-08-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movielinks'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['movie_id'], include=('rating',), name='rating_movie_id_index'),
        ),
    ]
