# Generated by Django 5.0.7 on 2024-07-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_moviegenometag_movie_genome_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenometag',
            name='user_id',
            field=models.PositiveIntegerField(verbose_name='User ID'),
        ),
    ]
