# Generated by Django 5.0.7 on 2024-08-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_release_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=8, null=True)),
                ('tmdb_id', models.CharField(max_length=15, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_link', to='movies.movie', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Movie Links',
                'verbose_name_plural': 'Movies Links',
            },
        ),
    ]
